version: '3.8'

services:
  app:
    build: .
    container_name: parking-service-app
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=parking_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - parking-network

  db:
    image: postgres:13
    container_name: parking-service-db
    environment:
      POSTGRES_DB: parking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - parking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  seed:
    build: .
    container_name: parking-service-seed
    depends_on:
      app:
        condition: service_started
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=parking_db
    command: npm run seed
    networks:
      - parking-network

networks:
  parking-network:
    driver: bridge

volumes:
  postgres-data:
